server:
    port: 8080
    servlet:
        context-path: /hotel
spring:
    datasource:
        url: ${DBMS_CONNECTION}
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: ${DBMS_USERNAME}
        password: ${DBMS_PASSWORD}
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true