server:
    port: 8080
    servlet:
        context-path: /hotel
spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/hotel_manager"
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: "root"
        password: "nqluong"
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true